d: 11
n_samples: 5000000
batch_size: 1024
discount: 0.9
log_dir: '/tmp/rl_laprepr/log'
total_train_steps: 80000
print_freq: 1000
save_freq: 10000
max_episode_steps: 50
seed: 1234
env_name: GridRoom-16
env_family: Grid-v0
lr: 0.001
use_wandb: True
hidden_dims:
  - 256
  - 256
  - 256
activation: relu
use_layer_norm: False
eigval_precision_order: 16
reduction_factor: 1
permute_step: 20000
direct_rotation: True
save_eig: True
save_model: False
save_model_every: 100000
do_plot_eigenvectors: False
obs_mode: xy
window_size: 128
algorithm: ggdo
asymmetric_normalization: False
coefficient_normalization: True
barrier_initial_val: 1.0
